AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend for diploma SWAPI

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 90

Resources:
  BackendDynamoDBFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: backend_dynamodb/
      Handler: app.lambda_handler
      Runtime: python3.8
      # Architectures:
      #   - x86_64
      Environment:
        Variables:
          TABLE_NAME: "starwars"
      Events:
        BackendDynamoDB:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: get
        UpdateDynamoDB:
          Type: Api
          Properties:
            Path: /update
            Method: put

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BackendDynamoDBApi:
    Description: "API Gateway endpoint URL for Prod stage for BackendDynamoDB function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  BackendDynamoDBFunction:
    Description: "BackendDynamoDB Lambda Function ARN"
    Value: !GetAtt BackendDynamoDBFunction.Arn
  BackendDynamoDBFunctionIamRole:
    Description: "Implicit IAM Role created for BackendDynamoDB"
    Value: !GetAtt BackendDynamoDBFunctionRole.Arn
